apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  selector:
    matchLabels:
      app: httpserver
  replicas: 1
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: node-httpserver
        image: nevincleetus/httpserver:1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"
