apiVersion: v1
kind: Service
metadata:
  name: httpserver-service
spec:
  type: NodePort
  selector:
    app: httpserver

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100

