apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    collectord.io/logs-override.1-match: ^(\d{1,3}\.){3}\d{1,3}
    collectord.io/logs-override.1-source: /kubernetes/nginx/web-log
spec:
  containers:
  - name: nginx
    image: nginx
