apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: frontendapp
    image: nevincleetus/frontend
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: backendapp
    image: nevincleetus/backend
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
